config/routes.rb
Rails.application.routes.draw do

  root 'page#helloworld'

  get '/about' => 'page#about'
  get 'issues/new' => 'issues#new'
  get 'issues' => 'issues#index', as: :issues
  post 'issues' => 'issues#create'
  get 'issues/:id' => 'issues#show', as: :issue
  delete 'issues/:id' => 'issues#destroy'

end

app/models/issue.rb
class Issue < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def show
    @issue= Issue.find(params[:id])
  end

  def destroy
    i=Issue.find(params[:id])
    i.destroy
    redirect_to :root
  end

  def new
    @issue=Issue.new
  end

  def create
    Issue.create(issue_params)
    redirect_to :root
  end

  private
  def issue_params
    params.require(:issue).permit(:title, :content)
  end

end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def helloworld
    @issues=Issue.all
  end
  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/issues/new.html.erb
<%= form_for @issue do |f|%>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :content %>
<%= f.text_area :content %>
<%= f.submit %>
<% end %>

app/views/issues/show.html.erb
<div>
    <h5><%=@issue.title%></h5>
    <%=link_to 'Destroy', issue_path(@issue) , method: :delete,data:{confirm:'Are you sure ?'}%>
    <p><%=@issue.content%></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meetup</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>Welcome To Rails Meetup!</h1>
<%= yield %>
</body>
</html>

app/views/page/_issue_list.html.erb
<div style="margin-top: 10px">
  <% issues.each do |i| %>
    <div>
      title:<%=link_to i.title ,issue_path(i) %>
      comment:5
    </div>
  <% end %>
</div>

app/views/page/about.html.erb
<div style="margin-top: 10px">this is about page !</div>

app/views/page/helloworld.html.erb
<div style="margin-top: 10px">HelloWorld!</div>
<li style="margin-top: 10px"><%=link_to "About","/about"%></a></li>

<div>
  <%= render partial: 'issue_list',locals: {issues:@issues}%>
</div>
<div style="margin-top: 10px">
  <%= link_to "发布新活动","/issues/new"%>
</div>